services:
  # db***
  # test_home_users
  # postgres16:
  #   container_name: postgres16
  #   image: postgres:16-alpine
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     - POSTGRES_USER=paulov
  #     - POSTGRES_PASSWORD=paulovroot
  #     - POSTGRES_DB=db_msvc_users_prod
  #   volumes:
  #     - data-postgres:/var/lib/postgresql/data
  #   restart: always
  # test_home_users

  postgres16ac:
    container_name: postgres16ac
    image: postgres:16-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=paulov
      - POSTGRES_PASSWORD=paulovroot
      - POSTGRES_DB=db_msvc_avaluos_catastros
    volumes:
      - data-postgres-ac:/var/lib/postgresql/data
    restart: always

  postgres16b:
    container_name: postgres16b
    image: postgres:16-alpine
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=paulov
      - POSTGRES_PASSWORD=paulovroot
      - POSTGRES_DB=db_msvc_binnacle
    volumes:
      - data-postgres-b:/var/lib/postgresql/data
    restart: always

  # apps***
  msvc-users-prod:
    container_name: msvc-users-prod
    #prod----------------
    # image: paulovivar/msvc-users-prod:latest
    #dev-----------------
    # image: users:latest
    build: 
      context: ./
      dockerfile: ./msvc-users-prod/Dockerfile
    ports:
      - 8001:8001
    #prod----------------
    # environment: 
    #   - PORT=8001
    #   - DB_HOST=172.26.11.35:5432
    #   - DB_DATABASE=municipio
    #   - DB_USERNAME=postgres
    #   - DB_PASSWORD=
    #   - SPRING_MAIL_PASSWORD=eqwyqgalkzsykgvi
    #   - PROCEDURES_URL=msvc-avaluos-catastros:8002/api/v1/procedures
    #dev-----------------
    env_file:
      - ./msvc-users-prod/.env
    # test_home_users
    # depends_on:
    #   - postgres16
    # test_home_users
    restart: always

  msvc-avaluos-catastros:
    container_name: msvc-avaluos-catastros
    #prod----------------
    #image: paulovivar/msvc-avaluos-catastros:latest
    #dev-----------------
    # image: avaluos-catastros:latest
    build: 
      context: ./
      dockerfile: ./msvc-avaluos-catastros/Dockerfile
    ports:
      - 8002:8002
    #prod----------------
    environment:
      - SPRING_CLOUD_CONFIG_ENABLED=false
    # environment: 
    #   - PORT=8002
    #   - DB_HOST=postgres16ac:5432
    #   - DB_DATABASE=db_msvc_avaluos_catastros
    #   - DB_USERNAME=paulov
    #   - DB_PASSWORD=paulovroot
    #   - USERS_URL=msvc-users-prod:8001/api/v1/users
    #dev-----------------
    env_file: 
      - ./msvc-avaluos-catastros/.env
    depends_on:
      - postgres16ac
      - msvc-users-prod
    restart: always

  msvc-binnacle:
    container_name: msvc-binnacle
    #prod----------------
    #image: paulovivar/msvc-binnacle:latest
    #dev-----------------
    # image: binnacle:latest
    build: 
      context: ./
      dockerfile: ./msvc-binnacle/Dockerfile
    ports:
      - 8003:8003
    #prod----------------
    # environment: 
    #   - PORT=8003
    #   - DB_HOST=postgres16b:5432
    #   - DB_DATABASE=db_msvc_binnacle
    #   - DB_USERNAME=paulov
    #   - DB_PASSWORD=paulovroot
    #   - USERS_URL=msvc-users-prod:8001/api/v1/users
    #dev-----------------
    env_file: 
      - ./msvc-binnacle/.env
    depends_on:
      - postgres16b
      - msvc-users-prod
    restart: always

volumes:
  # test_home_users
  # data-postgres:
  #   name: data-postgres
  # test_home_users
  data-postgres-ac:
    name: data-postgres-ac
  data-postgres-b:
    name: data-postgres-b
