spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}
      client:
        registration:
          msvc-users-prod:
            provider: spring
            client-id: users-prod
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: ${LB_USERS_ISSUER_URI:http://127.0.0.1:8001}/authorized
            scope: read
            client-name: msvc-users-prod
        provider:
          spring:
            issuer-uri: ${LB_AUTH_ISSUER_URI:http://127.0.0.1:9000}
              